"""
Master inventory of demographic variables for the election research engine.

This is the single source of truth for *what we want*, not what we have.
Run `build_demographic_catalog` to export CSVs, then `audit_demographic_coverage`
to see which raw/processed files exist on disk.

Each entry tracks:
    variable_id, variable_name, category, source, source_year,
    geography_level, priority, description,
    raw_file_expected, processed_column, status
"""

# -----------------------------------------------------------------------------
# Sources (used in variable rows and in demographic_sources_master.csv)
# -----------------------------------------------------------------------------

SOURCE_CENSUS_2011 = "CENSUS_2011"
SOURCE_NFHS_5 = "NFHS_5"
SOURCE_MOSPI = "MOSPI"
SOURCE_RBI = "RBI"

GEO_STATE = "state"
GEO_STATE_DISTRICT = "state_district"
GEO_DISTRICT = "district"
GEO_NATIONAL = "national"

STATUS_PLANNED = "planned"
STATUS_RAW_AVAILABLE = "raw_available"
STATUS_PROCESSED = "processed_available"

# Substring hints for matching uploaded files (case-insensitive) in raw folders.
# The audit treats a variable as "raw found" if any file in that source's folder
# contains this substring in its filename.

DEMOGRAPHIC_VARIABLES = [
    # --- Population (Census 2011) ---
    {
        "variable_id": "POP_TOTAL",
        "variable_name": "Total population",
        "category": "Population",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Total population by state",
        "raw_file_expected": "India State Population",
        "processed_column": "population_total",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "POP_DENSITY",
        "variable_name": "Population density",
        "category": "Population",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Persons per sq km",
        "raw_file_expected": "India State Population",
        "processed_column": "population_density",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "URBAN_PCT",
        "variable_name": "Urban population share",
        "category": "Population",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Urban population as % of total",
        "raw_file_expected": "India State Population",
        "processed_column": "urban_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "RURAL_PCT",
        "variable_name": "Rural population share",
        "category": "Population",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Rural population as % of total",
        "raw_file_expected": "India State Population",
        "processed_column": "rural_pct",
        "status": STATUS_PLANNED,
    },
    # --- Religion (Census 2011) ---
    {
        "variable_id": "HINDU_PCT",
        "variable_name": "Hindu population share",
        "category": "Religion",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Hindu % of population",
        "raw_file_expected": "DDW00C",
        "processed_column": "hindu_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "MUSLIM_PCT",
        "variable_name": "Muslim population share",
        "category": "Religion",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Muslim % of population",
        "raw_file_expected": "DDW00C",
        "processed_column": "muslim_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "CHRISTIAN_PCT",
        "variable_name": "Christian population share",
        "category": "Religion",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Christian % of population",
        "raw_file_expected": "DDW00C",
        "processed_column": "christian_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "SIKH_PCT",
        "variable_name": "Sikh population share",
        "category": "Religion",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Sikh % of population",
        "raw_file_expected": "DDW00C",
        "processed_column": "sikh_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "BUDDHIST_PCT",
        "variable_name": "Buddhist population share",
        "category": "Religion",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Buddhist % of population",
        "raw_file_expected": "DDW00C",
        "processed_column": "buddhist_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "JAIN_PCT",
        "variable_name": "Jain population share",
        "category": "Religion",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Jain % of population",
        "raw_file_expected": "DDW00C",
        "processed_column": "jain_pct",
        "status": STATUS_PLANNED,
    },
    # --- Social (Census 2011) ---
    {
        "variable_id": "SC_PCT",
        "variable_name": "Scheduled caste share",
        "category": "Social",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "SC population as % of total",
        "raw_file_expected": "PCA",
        "processed_column": "sc_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "ST_PCT",
        "variable_name": "Scheduled tribe share",
        "category": "Social",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "ST population as % of total",
        "raw_file_expected": "PCA",
        "processed_column": "st_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "SEX_RATIO",
        "variable_name": "Sex ratio",
        "category": "Social",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Females per 1000 males",
        "raw_file_expected": "India State Population",
        "processed_column": "sex_ratio",
        "status": STATUS_PLANNED,
    },
    # --- Education (Census 2011) ---
    {
        "variable_id": "LITERACY_RATE",
        "variable_name": "Literacy rate",
        "category": "Education",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Overall literacy %",
        "raw_file_expected": "literacy",
        "processed_column": "literacy_rate",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "MALE_LITERACY",
        "variable_name": "Male literacy",
        "category": "Education",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Male literacy %",
        "raw_file_expected": "literacy",
        "processed_column": "male_literacy",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "FEMALE_LITERACY",
        "variable_name": "Female literacy",
        "category": "Education",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Female literacy %",
        "raw_file_expected": "literacy",
        "processed_column": "female_literacy",
        "status": STATUS_PLANNED,
    },
    # --- Age (Census 2011) ---
    {
        "variable_id": "YOUTH_PCT",
        "variable_name": "Youth share",
        "category": "Age",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Share of population in youth age bands",
        "raw_file_expected": "PCA_AY",
        "processed_column": "youth_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "WORKING_AGE_PCT",
        "variable_name": "Working-age share",
        "category": "Age",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Share in working-age bands",
        "raw_file_expected": "PCA_AY",
        "processed_column": "working_age_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "ELDERLY_PCT",
        "variable_name": "Elderly share",
        "category": "Age",
        "source": SOURCE_CENSUS_2011,
        "source_year": 2011,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Share in elderly age bands",
        "raw_file_expected": "PCA_AY",
        "processed_column": "elderly_pct",
        "status": STATUS_PLANNED,
    },
    # --- NFHS-5 (state indicators) ---
    {
        "variable_id": "INTERNET_PCT",
        "variable_name": "Internet access",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Households with internet",
        "raw_file_expected": "internet",
        "processed_column": "internet_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "BANK_ACCOUNT_PCT",
        "variable_name": "Bank account access",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Households with bank account",
        "raw_file_expected": "bank",
        "processed_column": "bank_account_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "MOBILE_PHONE_PCT",
        "variable_name": "Mobile phone access",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Households with mobile phone",
        "raw_file_expected": "mobile",
        "processed_column": "mobile_phone_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "WOMEN_SECONDARY_EDU_PCT",
        "variable_name": "Women with secondary education",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Women age 15-49 with secondary+ education",
        "raw_file_expected": "education",
        "processed_column": "women_secondary_edu_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "FERTILITY_RATE",
        "variable_name": "Total fertility rate",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Total fertility rate (TFR)",
        "raw_file_expected": "fertility",
        "processed_column": "fertility_rate",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "ELECTRICITY_PCT",
        "variable_name": "Electricity access",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Households with electricity",
        "raw_file_expected": "electricity",
        "processed_column": "electricity_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "LPG_PCT",
        "variable_name": "LPG/clean fuel access",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "medium",
        "description": "Households using LPG/clean cooking fuel",
        "raw_file_expected": "lpg",
        "processed_column": "lpg_pct",
        "status": STATUS_PLANNED,
    },
    {
        "variable_id": "IMPROVED_SANITATION_PCT",
        "variable_name": "Improved sanitation",
        "category": "NFHS",
        "source": SOURCE_NFHS_5,
        "source_year": 2021,
        "geography_level": GEO_STATE,
        "priority": "high",
        "description": "Households with improved sanitation facility",
        "raw_file_expected": "sanitation",
        "processed_column": "improved_sanitation_pct",
        "status": STATUS_PLANNED,
    },
]

# Rows for demographic_sources_master.csv (built by build_demographic_catalog.py).
DEMOGRAPHIC_SOURCES = [
    {
        "source_id": SOURCE_CENSUS_2011,
        "source_name": "Census of India 2011",
        "description": "Population, religion, SC/ST, literacy, age structure",
        "default_geography_level": GEO_STATE_DISTRICT,
        "notes": "Primary baseline; district tables can be rolled up to state.",
    },
    {
        "source_id": SOURCE_NFHS_5,
        "source_name": "NFHS-5 (2019-21)",
        "description": "Health, assets, education, fertility, sanitation",
        "default_geography_level": GEO_STATE,
        "notes": "Complements Census with recent household behaviour indicators.",
    },
    {
        "source_id": SOURCE_MOSPI,
        "source_name": "MoSPI / NAS / state accounts",
        "description": "Macro and state economic statistics",
        "default_geography_level": GEO_STATE,
        "notes": "Optional enrichment for economic context.",
    },
    {
        "source_id": SOURCE_RBI,
        "source_name": "Reserve Bank of India",
        "description": "Banking, credit, financial inclusion proxies",
        "default_geography_level": GEO_STATE,
        "notes": "Optional; may overlap with NFHS on financial access.",
    },
    {
        "source_id": "PLFS",
        "source_name": "Periodic Labour Force Survey",
        "description": "Employment, labour force participation",
        "default_geography_level": GEO_STATE,
        "notes": "Future: labour market controls.",
    },
    {
        "source_id": "SECC",
        "source_name": "Socio-Economic Caste Census 2011",
        "description": "Deprivation, housing, asset proxies at rural granularity",
        "default_geography_level": GEO_DISTRICT,
        "notes": "Future: caste/deprivation where Census is coarse.",
    },
]

# Map source_id -> warehouse raw subdirectory name(s) to scan.
SOURCE_RAW_DIRS = {
    SOURCE_CENSUS_2011: ("census_2011",),
    SOURCE_NFHS_5: ("nfhs",),
    SOURCE_MOSPI: ("mospi",),
    SOURCE_RBI: ("rbi",),
}

STATE_DEMOGRAPHICS_MASTER_COLUMNS = [
    "state",
    "census_state_code",
    "nfhs_state_code",
    "population_total",
    "population_density",
    "urban_pct",
    "rural_pct",
    "hindu_pct",
    "muslim_pct",
    "christian_pct",
    "sikh_pct",
    "buddhist_pct",
    "jain_pct",
    "sc_pct",
    "st_pct",
    "sex_ratio",
    "literacy_rate",
    "male_literacy",
    "female_literacy",
    "youth_pct",
    "working_age_pct",
    "elderly_pct",
    "internet_pct",
    "bank_account_pct",
    "mobile_phone_pct",
    "women_secondary_edu_pct",
    "fertility_rate",
    "electricity_pct",
    "lpg_pct",
    "improved_sanitation_pct",
]
